### ISSUE TITLE
winsible playbook ImportError: No module named pwd

### ISSUE THREAD

**Issue by rsrini7** [pjeby/winsible#1]
After install i am facing below issue. Any idea ?

Traceback (most recent call last):
  File "D:\InstallsEdu\Python27\Scripts\winsible-playbook-script.py", line 9, in
 <module>
    load_entry_point('winsible==0.1.0', 'console_scripts', 'winsible-playbook')(
)
  File "D:\InstallsEdu\Python27\lib\site-packages\pkg_resources.py", line 339, i
n load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\InstallsEdu\Python27\lib\site-packages\pkg_resources.py", line 2470,
in load_entry_point
    return ep.load()
  File "D:\InstallsEdu\Python27\lib\site-packages\pkg_resources.py", line 2184,
in load
    ['**name**'])
  File "D:\InstallsEdu\Python27\lib\site-packages\winsible__init__.py", line 6,
 in <module>
    import ansible.constants as C
  File "D:\InstallsEdu\Python27\lib\site-packages\ansible\constants.py", line 19
, in <module>
    import pwd
ImportError: No module named pwd

**Comment by pjeby** [comment]
Ansible (and therefore winsible) does not work with the Windows version of Python.  You need to install and run them with the Cygwin version of Python.
